### ISSUE TITLE
Bug in read collapsing?

### ISSUE THREAD

**Issue by tsibley** [hbc/li_hiv#1]
I believe there's a small bug in part of the [read collapsing code](https://github.com/hbc/li_hiv/blob/master/scripts/check-virusinfo.R#L15):

``` R
group_by(read_name) %>% mutate(read_count=n()) %>% filter(mapq == max(mapq)) %>%
```

The maximum mapq may be shared by more than one line, and so in some cases this permits more than one alignment per read through.  I believe there are instances of this in the Sunshine, et al. data.

**Comment by roryk** [comment]
Hi Thomas,

Awesome catch, and you're totally right. I just reran everything on one of the sets of data and took the average of the number of multiple hits for each read for each site. It looks like for the vast majority of sites, especially the single alignment of evidence sites, it has no effect, but for some sites it can overestimate the evidence a bit.

**Comment by tsibley** [comment]
Yep, I didn't expect it to have much effect, but figured it was worth pointing out.  Thanks for responding so quickly!

**Comment by roryk** [comment]
Thanks a lot for digging into it and pinging me about it.
